### ISSUE TITLE
IbisML - Interactive Mode

### ISSUE THREAD

**Issue by sfc-gh-twhite** [ibis-project/ibisml#13]
After performing a fit and a transform with a recipe, the return looks like this, even in interactive mode.

```python
In [1]: import ibisml as ml
   ...: from ibis.interactive import *
   ...: 
   ...: con = ibis.duckdb.connect()
   ...: 
   ...: diamonds = con.read_csv(
   ...:     "https://raw.githubusercontent.com/tidyverse/ggplot2/main/data-raw/diamonds.csv"
   ...: )
   ...: 
   ...: rec = ml.Recipe(ml.CategoricalEncode("cut"))
   ...: rec.fit(diamonds).transform(diamonds)
Out[1]: 
TransformResult:
- Features {
    carat    float64
    color    string
    clarity  string
    depth    float64
    table    float64
    price    int64
    x        float64
    y        float64
    z        float64
    cut      int64
}
```

It's possible to do `rec.fit(diamonds).transform(diamonds).table` to see the result, but I wasn't sure this was the expected behavior using interactive mode.

**Comment by gforsyth** [comment]
Thanks for reporting @sfc-gh-twhite ! 

I'm not sure if we had thought about behavior in interactive mode (or at least I can't remember).  Would you prefer it showed you the result interactively?

**Comment by sfc-gh-twhite** [comment]
It might be useful to have it available interactively! It's easy to do a `.table` method and get the object that way, but I guess it would be important for people to understand that behavior was occurring automatically.

**Comment by jcrist** [comment]
After the refactor we no longer have a `TransformResult` type (or any similar abstraction). I think this can be closed, as it no longer makes sense with the new API.
