### ISSUE TITLE
Applying custom transforms

### ISSUE THREAD

**Issue by skrawcz** [ibis-project/ibisml#18]
What is the plan for allowing custom transforms for feature engineering to be applied?

These can range from something like:

```python
def is_high_roller(order_value: float) -> bool:
    return order_value > 1000.0
```

to more complex where multiple successive transforms are required:

```python
def survey_features(raw_json: str) ->  dict:
    return json.loads(raw_json)["survey"]

def one_hot_encode(survey_features: dict) -> list:
    return ...  # takes in survey features an one hot encodes them...
```

Invariably not everything is translatable to SQL, so you need some runtime to execute things with... 

Note: I drive [hamilton](https://github.com/DAGWorks-Inc/hamilton) which could have an integration with ibis...

**Comment by lostmygithubaccount** [comment]
hello @skrawcz! this is generally what user-defined functions (UDFs) are for. they are supported in Ibis already: https://ibis-project.org/reference/scalar-udfs -- though in your first example that could just be a mutation:

```python
t = t.mutate(is_high_roller=(t.order_value > 1000))
```

UDFs are very useful though, and can be generic Python or vectorized pandas/PyArrow, or builtin to the database (like [`list_cosine_similarity` in DuckDB](https://duckdb.org/docs/test/functions/nested.html) which I used today)

we have some blogs showing off UDFs:

- used in here to make OpenAI API calls: https://ibis-project.org/posts/lms-for-data/
- used in here for ML predictions: https://ibis-project.org/posts/torch/#define-an-ibis-udf-that-predicts-fares
- used in here for a regex: https://ibis-project.org/posts/ibis-analytics/#directed-acyclic-graph-dag-and-inputoutput-management

we'd definitely be interested in a Hamilton integration

**Comment by skrawcz** [comment]
Awesome -- I didn't see reference to UDFs so I didn't want to assume (and it looks like UDF support has improved a lot since last I looked) -- will take a look and see if I have more questions.

Otherwise I have documention request to articulate when to use what, e.g. recipes versus your own UDFs, etc.

**Comment by jcrist** [comment]
Cody's response is correct, we have `ml.Mutate` and `ml.MutateAt` calls for handling custom row-level transforms. For more complicated steps we should support users implementing their own `ml.Step` subclasses (still need docs on how to do that - I'll open up a follow-up ticket on that). For now I don't think there's anything left to do here - closing.
