### ISSUE TITLE
Docstrings + Examples + Help Get Started

### ISSUE THREAD

**Issue by IndexSeek** [ibis-project/ibisml#21]
There are some pretty good documented functions in the step functions. Is there another area to which you would like to add some docstrings? I'm unsure how many people would need/reference any of the inner functions, or if they would need to see docstrings for the transform functions. 

We could do a small "getting-started" section, why IbisML?, or "IbisML for scikit-learn" users. 

Happy to mock up a few small examples. :)

**Comment by lostmygithubaccount** [comment]
I'll leave the specifics to others but you can expect a lot more work in IbisML happening in the coming weeks! we'd like to announce it (while released on PyPI and everything public here, we haven't made any noise) by the end of March, though it could be a little later depending on the work needed

**Comment by IndexSeek** [comment]
Thanks @lostmygithubaccount! I am looking forward to the upcoming announcements and am happy to help however possible with bandwidth!
