### ISSUE TITLE
Push release 0.2.0 to Pypi

### ISSUE THREAD

**Issue by zilto** [ibis-project/ibisml#22]
I was hitting an error trying in `ibisml.steps` with the import of `ibis.expr.deferred.Deferred`. 

I see that this was fixed on the GitHub release 0.2.0 from November 2023. However, the[ latest version on Pypi](https://pypi.org/project/ibisml/) is 0.1.0 from September 2023.

**Comment by gforsyth** [comment]
Thanks for flagging this @zilto -- I cut that release and forgot that we hadn't yet set up an action to automatically push releases to PyPI.  We'll get 0.2.0 up on PyPI shortly.

**Comment by gforsyth** [comment]
0.2.0 is now available on PyPI.  Thanks again!
https://pypi.org/project/ibisml/0.2.0/
